export interface UmsatzDaten {
  kunde: string, 
  vermittler: string,
  objekt: string,
  vertreter: string,
  key1: string,
  key2: string,
  key3: string,
  key4: string,
  key5: string,
  r_key1: number,
  r_key2: number,
  r_key3: number,
  r_key4: number,
  r_key5: number,
  r_key6?: number,
  r_key7?: number,
  r_key8?: number,
  r_key9?: number,
  r_kunde: number,
  r_vertreter: number,
  r_vermittler: number,
  r_objekt: number,
  _datumvon: string,
  _datumbis: string,
  sicht:string
}